spring.application.name=vacation-scheduler
spring.datasource.url=jdbc:postgresql://localhost:5432/vacation_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC1hdXRoZW50aWNhdGlvbi0yMDI2}
jwt.expiration=3600000