spring.application.name=vacation-scheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/vacation_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

jwt.secret=UxZKacHKlRyzZvLvKqrAiQTMBiYXTAQ9Ck5gZutkUEMA9T0xq/FOUNpXSKA6lubzH1oe/CZ+W6z5RSKe4tyUeA==
jwt.expiration=3600000

server.port=8080